<script src="{{ url('/website') }}/js/reportsbootstrap.min.js"></script>
<script src="{{ url('/website') }}/js/jquery-3.7.1.js"></script>
<script src="{{ url('/website') }}/js/reportsdataTables.js"></script>
<script src="{{ url('/website') }}/js/dataTables.rowGroup.min.js"></script>
<script src="{{ url('/website') }}/js/dataTables.fixedColumns.js"></script>
<script src="{{ url('/website') }}/js/fixedColumns.dataTables.js"></script>
<script src="{{ url('/website') }}/js/dataTables.buttons.js"></script>
<script src="{{ url('/website') }}/js/buttons.dataTables.js"></script>
<script src="{{ url('/website') }}/js/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
<script src="{{ url('/website') }}/js/vfs_fonts.js"></script>
<script src="{{ url('/website') }}/js/buttons.html5.min.js"></script>
<script src="{{ url('/website') }}/js/buttons.colVis.min.js"></script>

<script>
    var username = @json(auth()->user()->first_name . ' ' . auth()->user()->last_name); // Replace this with dynamic username (e.g., from session)
    var currentDate = new Date().toLocaleString(); // Get formatted date

    new DataTable('#example', {
    dom: "<'row'<'col-sm-3'l><'col-sm-6 text-center'B><'col-sm-3'f>>" + "<'row'<'col-sm-12'tr>>" + "<'row'<'col-sm-5'i><'col-sm-7'p>>",
    pageLength: 20,
    "lengthMenu": [[20, 50, 100, -1], [20, 50, 100, "All"]], // Defines available page sizes
    fixedColumns: {
        start: 2
    },
    scrollX: true,
    buttons: [
        'copyHtml5',
        {
            extend: 'excelHtml5',
            exportOptions: {
                columns: ':not(.noExport)', // Excludes columns with class "noExport"
                modifier: {
                        search: 'applied',
                        order: 'applied'
                    },
            },
        },
        'csvHtml5',
        {
            extend: 'pdfHtml5',
            text: 'PDF',
            exportOptions: {
                columns: ':visible:not(.noExport)',
                modifier: {
                        search: 'applied',
                        order: 'applied'
                    },
                
            },
            customize: function(doc) {
                // rest indexing
                var tableNode = doc.content[1].table.body;

                // Loop through table rows and reset numbering in the first column
                for (var i = 1; i < tableNode.length; i++) {
                    tableNode[i][0].text = i; // Set the first column as the row number
                }
                
                doc['header'] = function(currentPage, pageCount, pageSize) {
                        return [
                            {
                                text: 'Generated by: ' + username + '\n' + currentDate,
                                alignment: 'right',
                                margin: [0, 10, 10, 0], // [left, top, right, bottom]
                                fontSize: 10,
                                italics: true
                            }
                        ];
                    };
            },

            title: 'Egy Finance Jobs | Users Report', // Custom title
            orientation: 'portrait', // Use 'portrait' or 'landscape'
            pageSize: 'A4', // Set page size           
           
        },
        { extend: 'colvis', className: 'btn btn-default', text: 'Display' },
    ]
});
</script>

</html>